### ISSUE TITLE
resetDatabase cause error on meteor 1.6.1

### ISSUE THREAD

**Issue by nikolai-berezin** [xolvio/cleaner#20]
Just upgraded my meteor project to version 1.6.1 and my meteor server tests starts to fail.
They are work fine on version 1.6.0.1 and fail on 1.6.1 with error on calling beforeEach hook:
`Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test`
Tried to use this.timeout() function with no luck. 
BTW, I'm using meteortesting:mocha package.

**Comment by artgo** [comment]
+1

**Comment by brookback** [comment]
*Cross-posted from https://github.com/meteor/meteor/issues/9630.*

We're getting the same error on Meteor 1.6.1 with the `cleaner` package. This is the test output:

```
I20180208-16:57:07.459(1)?   Namespace
I20180208-16:57:07.460(1)?     publication
=> Meteor server restarted
      1) "before each" hook: wrappedFunction for "should publish"
I20180208-16:57:09.470(1)?
I20180208-16:57:09.470(1)?
I20180208-16:57:09.471(1)?   0 passing (2s)
I20180208-16:57:09.471(1)?   1 failing
I20180208-16:57:09.471(1)?
I20180208-16:57:09.471(1)?   1) publication "before each" hook: wrappedFunction for "should publish":
I20180208-16:57:09.472(1)?      Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

The test code includes:

```js
import { resetDatabase } from 'meteor/xolvio:cleaner';

beforeEach(() => {
    resetDatabase();
  });
});
```

The business logic and test code was untouched in the upgrade to 1.6.1.

The code in the `cleaner` package is quite short: https://github.com/xolvio/cleaner/blob/master/cleaner.js

Seems they're using `MongoInternals.defaultRemoteCollectionDriver().mongo.db` and `Meteor.wrapAsync` to remove all documents from a collection. Perhaps have the former changed in 1.6.1? Also, we've got [`Collection#rawCollection`](https://docs.meteor.com/api/collections.html#Mongo-Collection-rawCollection) now instead.

I'd guess something's failing inside the cleaner package, and perhaps due to https://github.com/meteortesting/meteor-mocha/issues/47, it becomes the 2000ms error reported in Mocha.

**Comment by brookback** [comment]
Yep, I'm seeing now that [this line](https://github.com/xolvio/cleaner/blob/master/cleaner.js#L26) (`remove()`) never finishes. It's wrapped in `Meteor.wrapAsync`, but even when running as a regular async function, it never finishes.

**Comment by brookback** [comment]
Ok, I found it: changing line 26 to

```js
remove({}, {});
```

makes it work 🎉 The second param symbolises an options object.

I did a `console.log` of `remove.toString()` in the cleaner package, and it turns out the function signature is:

```
remove = (selector, options, callback)
```

If `typeof callback === 'function'`, the function will call it. In our case, `Meteor.wrapAsync` made the last parameter, `options`, become a callback, and the "real" callback parameter was `undefined`.

Either way, I don't know if this behaviour changed in Meteor 1.6.1, but passing a second param to `remove` fixes it.

**Comment by mikkelking** [comment]
Your fix doesn't seem to work... 

`      remove();` 

does work as per @FKint's fork

**Comment by juliedavila** [comment]
Could it be https://github.com/xolvio/cleaner/blob/master/.versions#L3?

As per the 1.6.1 release blog post, babel-compiler < 7 will cause problems.

**Comment by SamHatoum** [comment]
fixed in 0.3.2

**Comment by mikkelking** [comment]
I think I was wrong...

> remove();
> 
> does work as per @FKint's fork

This works because it doesn't actually remove any data. It needs an empty query to remove everything. So it made the problem go away, but I'm pretty sure it didn't address the actual problem.

**Comment by SamHatoum** [comment]
fixes (again) in 0.3.3 @mikkelking

**Comment by FKint** [comment]
@mikkelking I did not thoroughly examine the issue, but at least in my project it did reset the database. I added the following tests:
```
  beforeEach(function() {
    resetDatabase();
  });
  it('make one user', function() {
    Factory.create('emptyUser');
    assert.equal(Meteor.users.find().count(), 1);
  });
  it('make one more user', function() {
    Factory.create('emptyUser');
    assert.equal(Meteor.users.find().count(), 1);
  });
```
Which succeed, but fail if I remove `resetDatabase`.

While I agree that passing the empty query explicitly is better, I do think the package does not require it.

In cleaner.js, I printed the 'remove' function:
```
function (selector, options, callback) {
   var self = this;
 
   // Add ignoreUndefined
   if(this.s.options.ignoreUndefined) {
     options = shallowClone(options);
     options.ignoreUndefined = this.s.options.ignoreUndefined;
   }
 
   // Execute using callback
   if(typeof callback == 'function') return removeDocuments(self, selector, options, callback);
 
   // Return a Promise
   return new this.s.promiseLibrary(function(resolve, reject) {
     removeDocuments(self, selector, options, function(err, r) {
       if(err) return reject(err);
       resolve(r);
     });
   });
 }
```
, which I traced back to Node MongoDB native 2.2 (http://mongodb.github.io/node-mongodb-native/2.2/api/lib_collection.js.html)

The `removeDocuments` function seems to allow a null/undefined selector as per line 1235.

**Comment by mathieustan** [comment]
Hello everyone, 

We are using last xolvio:cleaner package (v0.3.3), and we still have this issue :( 
we rarely encounter this error locally, but more often on CircleCI (because it is probably less powerful than our computers).

Anyone else still have this error ? 

@samhatoum.

**Comment by lgandecki** [comment]
This problem could not have anything to do with powerfullness of CI/your local dev machine.
It's binary. It either works or not.

Looks to me like you just have your tests timeout.

**Comment by mathieustan** [comment]
@lgandecki It's weird because we encouter this issue after upgrading to Meteor 1.6.1. When we receive this error, next test fail with values still present in our database (clean didnt finish).

```
beforeEach(() => {
	resetDatabase();
	...
});
```

Logs: 
<img width="1180" alt="capture d ecran 2018-08-29 a 10 34 29" src="https://user-images.githubusercontent.com/38033090/44775992-54628200-ab77-11e8-9acf-a058ed971ba8.png">

We have 15 files instead of 12 (and previous test added 3 in DB)
